# Generated by Django 5.1.2 on 2024-10-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('public_key', models.BinaryField()),
            ],
        ),
        migrations.DeleteModel(
            name='Key',
        ),
    ]
