# Generated by Django 5.1.2 on 2024-10-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_userkey_delete_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserKey',
        ),
    ]
