# Generated by Django 5.1.2 on 2024-10-27 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0006_message_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
    ]
